# Generated by Django 3.0.7 on 2020-06-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubApp', '0002_auto_20200611_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lookup_name',
            field=models.CharField(default='tbd', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='keywords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='references',
            field=models.TextField(),
        ),
    ]
