# Generated by Django 3.0.7 on 2020-06-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubApp', '0003_auto_20200615_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='references',
        ),
    ]
